os: windows
language: bash
services: docker

script:
  - wmic cpu get VirtualizationFirmwareEnabled
  - choco install minikube
  - choco install virtualbox
  - choco install docker-machine
  - docker-machine create --virtualbox-no-vtx-check --driver virtualbox minikube
  - minikube start
  - minikube ip
  - minikube ssh "pwd"
