os: windows
language: bash
services: docker

script:
  - wmic cpu get VirtualizationFirmwareEnabled
  - choco install minikube
  - choco install virtualbox
  - minikube start
  - minikube ip
  - minikube ssh "pwd"
