os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - '"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine'
  - docker run hello-world
