os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - "& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine"
  - docker run hello-world
