os: windows
language: bash
services: docker

script:
  - wmic cpu get VirtualizationFirmwareEnabled
  - choco install minikube
  - minikube start --vm-driver=hyperv --hyperv-virtual-switch="Primary Virtual Switch"
  - minikube ip
  - minikube ssh "pwd"
