os: windows
language: bash
services: docker

script:
  - wmic cpu get VirtualizationFirmwareEnabled
  - choco install minikube
  - minikube start --vm-driver=hyperv
  - minikube ip
  - minikube ssh "pwd"
