os: windows
language: bash
services: docker

script:
  - docker version
  - docker images
  - docker info
  - echo /c/* | xargs -n1
  - ls "C:\"
  - '"/c/Program Files/Docker/Docker/DockerCli.exe" -Version'
  - '"/c/Program Files/Docker/Docker/DockerCli.exe" -SharedDrives'
  - '"/c/Program Files/Docker/Docker/DockerCli.exe" -SwitchLinuxEngine'
  - docker run hello-world
